version: 2.1

jobs:
  lint:
    docker:
      - image: cimg/node:14.15.3
    steps:
      - run: npm ci
      - run:
          name: lint
          command: npm run lint
      - run:
          name: type-check
          command: npm run type-check
      - run:
          name: type-check
          command: npm run type-check
  test:
    docker:
      - image: cimg/node:14.15.3
      - image: circleci/postgres:13-postgis-ram
    steps:
      - run: npm ci
      - run: npm run test

workflows:
  version: 2
  checks:
    jobs:
      - lint
      - test
